# Generated by Django 4.2.27 on 2025-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('categoria', models.CharField(blank=True, max_length=120)),
                ('kpi_conformidade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
