# Generated by Django 4.2.27 on 2025-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANALISE', 'Em Análise'), ('EM_TRATAMENTO', 'Em Tratamento'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=20)),
                ('data_abertura', models.DateField()),
                ('data_fecho', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
