# Generated by Django 4.2.27 on 2025-12-10 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utilizadores', '0001_initial'),
        ('nonconformidades', '0001_initial'),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naoconformidade',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilizadores.departamento'),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo'),
        ),
        migrations.AddField(
            model_name='naoconformidade',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncs_responsavel', to=settings.AUTH_USER_MODEL),
        ),
    ]
