# Generated by Django 4.2.27 on 2025-12-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('INTERNA_GLOBAL', 'Auditoria Interna Global'), ('INTERNA_PARCIAL', 'Auditoria Interna Parcial'), ('EXTERNA', 'Auditoria Externa'), ('FORNECEDOR', 'Auditoria a Fornecedor')], max_length=20)),
                ('ambito', models.TextField(help_text='Processos/áreas a auditar')),
                ('data_prevista_inicio', models.DateField()),
                ('data_prevista_fim', models.DateField()),
                ('data_real_inicio', models.DateField(blank=True, null=True)),
                ('data_real_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANEADA', 'Planeada'), ('PREPARACAO', 'Em Preparação'), ('EM_EXECUCAO', 'Em Execução'), ('RELATORIO', 'Elaboração Relatório'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='PLANEADA', max_length=20)),
                ('total_constatacoes', models.IntegerField(default=0)),
                ('nao_conformidades_encontradas', models.IntegerField(default=0)),
                ('oportunidades_melhoria', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordem', 'criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Constatacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('NAO_CONFORMIDADE', 'Não Conformidade'), ('OPORTUNIDADE_MELHORIA', 'Oportunidade de Melhoria'), ('OBSERVACAO', 'Observação'), ('PONTO_FORTE', 'Ponto Forte')], max_length=30)),
                ('criticidade', models.CharField(blank=True, choices=[('CRITICA', 'Crítica'), ('MAIOR', 'Maior'), ('MENOR', 'Menor')], max_length=10, null=True)),
                ('requisito_referencia', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('evidencia', models.TextField()),
                ('causa_possivel', models.TextField(blank=True)),
                ('data_identificacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_identificacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('requisito', models.TextField()),
                ('questao', models.TextField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFORME', 'Conforme'), ('NAO_CONFORME', 'Não Conforme'), ('NAO_APLICAVEL', 'Não Aplicável'), ('OPORTUNIDADE', 'Oportunidade de Melhoria')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('evidencia', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(blank=True, null=True)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordem', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normas_referencia', models.JSONField(default=list)),
                ('processos_detalhados', models.JSONField(default=list)),
                ('metodologia', models.TextField()),
                ('criterios_auditoria', models.TextField()),
                ('cronograma', models.JSONField(default=list)),
                ('recursos_necessarios', models.TextField(blank=True)),
                ('data_elaboracao', models.DateField()),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Plano de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='ProgramaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('versao', models.CharField(max_length=10)),
                ('data_elaboracao', models.DateField()),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído')], default='RASCUNHO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Programa de Auditoria',
                'verbose_name_plural': 'Programas de Auditoria',
                'ordering': ['-ano', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo_executivo', models.TextField()),
                ('objetivos', models.TextField()),
                ('metodologia', models.TextField()),
                ('ambito_detalhado', models.TextField()),
                ('sintese_resultados', models.TextField()),
                ('pontos_fortes', models.TextField(blank=True)),
                ('areas_melhoria', models.TextField(blank=True)),
                ('total_constatacoes', models.IntegerField()),
                ('nao_conformidades_criticas', models.IntegerField(default=0)),
                ('nao_conformidades_maiores', models.IntegerField(default=0)),
                ('nao_conformidades_menores', models.IntegerField(default=0)),
                ('oportunidades_melhoria', models.IntegerField(default=0)),
                ('conclusoes', models.TextField()),
                ('recomendacoes', models.TextField(blank=True)),
                ('anexos', models.JSONField(default=list)),
                ('data_elaboracao', models.DateField()),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='auditorias/relatorios/')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimentoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_acoes', models.TextField()),
                ('acoes_planejadas', models.IntegerField()),
                ('acoes_implementadas', models.IntegerField(default=0)),
                ('acoes_pendentes', models.IntegerField()),
                ('acoes_atrasadas', models.IntegerField(default=0)),
                ('prazo_implementacao', models.DateField()),
                ('data_verificacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], default='EM_ANDAMENTO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('auditoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimento', to='auditorias.auditoria')),
            ],
        ),
    ]
