# Generated by Django 4.2.27 on 2025-12-10 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilizadores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditorias', '0001_initial'),
        ('processos', '0001_initial'),
        ('nonconformidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimentoauditoria',
            name='responsavel_seguimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatorioauditoria',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatorioauditoria',
            name='auditoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='relatorioauditoria',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programaauditoria',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programas_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programaauditoria',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programas_elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoauditoria',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planos_auditoria_aprovados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planoauditoria',
            name='auditoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plano', to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='planoauditoria',
            name='elaborado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_auditoria_elaborados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemchecklist',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='auditorias.checklistauditoria'),
        ),
        migrations.AddField(
            model_name='constatacao',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constatacoes', to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='constatacao',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilizadores.departamento'),
        ),
        migrations.AddField(
            model_name='constatacao',
            name='identificada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='constatacao',
            name='item_checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constatacoes', to='auditorias.itemchecklist'),
        ),
        migrations.AddField(
            model_name='constatacao',
            name='nao_conformidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constatacoes_origem', to='nonconformidades.naoconformidade'),
        ),
        migrations.AddField(
            model_name='constatacao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo'),
        ),
        migrations.AddField(
            model_name='checklistauditoria',
            name='auditoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='auditorias.auditoria'),
        ),
        migrations.AddField(
            model_name='checklistauditoria',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilizadores.departamento'),
        ),
        migrations.AddField(
            model_name='checklistauditoria',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='processos.processo'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='auditor_lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_lideradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='auditores',
            field=models.ManyToManyField(blank=True, related_name='auditorias_participadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auditorias_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='departamentos',
            field=models.ManyToManyField(blank=True, related_name='auditorias', to='utilizadores.departamento'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='processos',
            field=models.ManyToManyField(blank=True, related_name='auditorias', to='processos.processo'),
        ),
        migrations.AddField(
            model_name='auditoria',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='auditorias.programaauditoria'),
        ),
        migrations.AlterUniqueTogether(
            name='programaauditoria',
            unique_together={('ano', 'versao')},
        ),
    ]
